### ISSUE TITLE
加载模型问题

### ISSUE THREAD

**Issue by Coder-nlper** [ymcui/Chinese-BERT-wwm#123]
你好我加载模型遇到，以下问题
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers  as tfs
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
>>> tfs.__version__
'2.2.2'
>>> tfs.BertModel.from_pretrained("chinese_rbt3_L-3_H-768_A-12")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_utils.py", line 367, in from_pretrained
    pretrained_model_name_or_path))
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory chinese_rbt3_L-3_H-768_A-12 or `from_tf` set to False
>>> config = BertConfig.from_json_file('./chinese_rbt3_L-3_H-768_A-12/config.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'BertConfig' is not defined
>>> config = tfs.BertConfig.from_json_file('./chinese_rbt3_L-3_H-768_A-12/config.json')
>>> tfs.BertModel.from_pretrained("chinese_rbt3_L-3_H-768_A-12/model.ckpt.index",from_tf=True,config=config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_utils.py", line 418, in from_pretrained
    model = cls.load_tf_weights(model, config, resolved_archive_file[:-6])  # Remove the '.index'
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_bert.py", line 116, in load_tf_weights_in_bert
    assert pointer.shape == array.shape
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertModel' object has no attribute 'shape'

一次按照README中的操作，发现不行。第二次看了transformers的接口，重新加载还是出错。发现代码默认调用的时候torch的，我感觉是transformers的bug。不知道你使用2.2.2版本有没有加载成功tf版本的

**Comment by Coder-nlper** [comment]
换了另一种方式加载，还是报错：
 tfs.TFBertModel.from_pretrained("chinese_rbt3_L-3_H-768_A-12/model.ckpt.index",config=config)
错误信息
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_tf_utils.py", line 309, in from_pretrained
    model.load_weights(resolved_archive_file, by_name=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1196, in load_weights
    'Weights may only be loaded based on topology into Models when '
NotImplementedError: Weights may only be loaded based on topology into Models when loading TensorFlow-formatted weights (got by_name=True to load_weights).

**Comment by ymcui** [comment]
加载本地模型：https://huggingface.co/transformers/main_classes/model.html#transformers.PreTrainedModel.from_pretrained

或者使用快速加载模式（transformers==2.10.0测试通过）：
```python
import transformers
model=transformers.BertModel.from_pretrained("hfl/rbt3")
```

**Comment by Coder-nlper** [comment]
我看了下transformers的源代码。
加载tensorflow模型必须加上from_tf=True。
tf.BertModel.from_pretrained('./hfl/rbt3',from_tf=True)
你那个应该是加载了torch，我这边按照你那个方式加载还是会碰到文件未找到错误
File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_utils.py", line 602, in from_pretrained
    pretrained_model_name_or_path,
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory ./hfl/rbt3 or `from_tf` set to False

加上from_tf之后，又是：

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_utils.py", line 673, in from_pretrained
    model = cls.load_tf_weights(model, config, resolved_archive_file[:-6])  # Remove the '.index'
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/transformers/modeling_bert.py", line 124, in load_tf_weights_in_bert
    assert pointer.shape == array.shape
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertModel' object has no attribute 'shape'


实在是没辙了～

**Comment by Coder-nlper** [comment]
> 加载本地模型：https://huggingface.co/transformers/main_classes/model.html#transformers.PreTrainedModel.from_pretrained
> 
> 或者使用快速加载模式（transformers==2.10.0测试通过）：
> 
> ```python
> import transformers
> model=transformers.BertModel.from_pretrained("hfl/rbt3")
> ```

你torch版本和tensorflow版本？
我这边torch==1.5.0
tensorflow==2.1.0

**Comment by ymcui** [comment]
torch 1.5.0
tensorflow 1.15.2
