### ISSUE TITLE
您好！请问这些模型支持transformers库的3.02版本加载吗？

### ISSUE THREAD

**Issue by BCWang93** [ymcui/Chinese-BERT-wwm#139]
你好！我最近在用transformers2.10加载你们的模型的时候就是正常的，但是当我使用transformers3.0.2加载这个模型的时候就会出错，错误的地方是对每句话进行embedding之后的长度不一样。。。我想问的就是你们的模型不支持transformers3.0吗？谢谢！

**Comment by ymcui** [comment]
3.x版本暂未测试，请在2.x版本下使用。或者可以去transformers目录中查看是否有2.x迁移到3.x的教程，这应该属于通用的问题，对于英文的BERT应该也是不能直接支持的。

**Comment by BCWang93** [comment]
> 3.x版本暂未测试，请在2.x版本下使用。或者可以去transformers目录中查看是否有2.x迁移到3.x的教程，这应该属于通用的问题，对于英文的BERT应该也是不能直接支持的。

谢谢，我去目录中看下，这是在transformers3.0下报的错误：
Trainable parameters: 102274668
248
250
252
252
248
250
252
252
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    run('./configs/base_config.json')
  File "train.py", line 88, in run
    main(config)
  File "train.py", line 66, in main
    trainer.train()
  File "/DATA2/disk1/wangbingchen/project/ccks2020-task8-pytorch/base/base_trainer.py", line 67, in train
    result = self._train_epoch(epoch)
  File "/DATA2/disk1/wangbingchen/project/ccks2020-task8-pytorch/trainer/trainer.py", line 59, in _train_epoch
    for batch_idx, batch_data in enumerate(self.train_iter):
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/DATA2/disk1/wangbingchen/project/ccks2020-task8-pytorch/data_process/military_data_process.py", line 179, in collate_fn
    text_token_ids = torch.LongTensor(np.array(text_token_ids))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
以后如果你们有时间可以优化一下，谢谢！
